### ISSUE TITLE
[Game Support] DL version of some games can't start, but package version works fine

### ISSUE THREAD

**Issue by ck1521** [kichikuou/xsystem4-android#1]
Related version: [Snapshot-20231201](https://github.com/kichikuou/xsystem4-android/releases/tag/Snapshot-20231201)

For some games, the package version and DL version showed different result:

**GALZOOアイランド**

- DL version  -- Won't start, error says the ALD format invalid
![3ece871273c85da93118f7b53ee59df1](https://github.com/kichikuou/xsystem4-android/assets/10858385/39dbba6c-644e-4483-9bf2-c269f9780631)
- Package version (ver 1.01) -- started successfully.

**超昂閃忍ハルカ**

- DL version  -- Won't start, error says the ALD format invalid
(error message later)
- Package version (ver 1.02) -- started successfully.

**ランス・クエスト + マグナム** (Not supported)

大番長 DL版
戦国ランス DL版 (not modded)
戦国ランス DL版 (with 大戦国ランス)
戦国ランス DL版 (with ルドラサウム大陸版)
worked fine though, haven't got any error yet.

**Comment by kichikuou** [comment]
Thank you for the report.

Could you download APK from https://github.com/kichikuou/xsystem4-android/actions/runs/7073300459 and try it out? I believe it will fix GALZOOアイランド and 超昂閃忍ハルカ.

**Comment by ck1521** [comment]
Closing issue as it's fixed
