### ISSUE TITLE
Msgskip file not working on second playthrough of Sengoku Rance

### ISSUE THREAD

**Issue by BeholdTheBiscuit** [kichikuou/xsystem4-android#10]
I just noticed this, as per title. I press the skip button, but nothing gets skipped. In the first playthrough it worked if I reloaded a save (during the same playthrough, I haven't tried loading a previous save from the second, and I can't because I deleted them).

xsystem35-sdl2 also lets you move a pointer with the black side of the screen, I wish we had the option, since the UI is not made for phones, and it's easy to misclick.

**Comment by kichikuou** [comment]
There was indeed a problem with the msgskip file not being saved correctly. I've released a new [snapshot](https://github.com/kichikuou/xsystem4-android/releases/tag/snapshot-20241013) that addresses this issue. Please try it out and let me know if it resolves the problem.

> xsystem35-sdl2 also lets you move a pointer with the black side of the screen, I wish we had the option, since the UI is not made for phones, and it's easy to misclick.

I'm not entirely sure I understand the request. Are you referring to using a Bluetooth or USB mouse connected to the device? Any clarification would be helpful.

**Comment by kichikuou** [comment]
XSystem35 was also ported to Android over a decade ago by someone other than me. Although I've never tried it, I've heard that it had a UI with a virtual mouse pointer. That may be what you remember.
