### ISSUE TITLE
MG's Rance 01- Quest for Hikari (remake) issue on android

### ISSUE THREAD

**Issue by KaroNiko** [kichikuou/xsystem4-android#6]
First of all, yet another thank you for adding support for this game, which is completely unexpected. I apologize for bothering you with another problem: this game proceeds perfectly up to the title (as in the photo), but then it gives an error during the opening theme (which can be heard in the background) and by clicking on this you exit the game. Of course, solving this trifle will be a piece of cake for you, I'm sure. 😉

![1723391957910](https://github.com/user-attachments/assets/28800eed-5f52-4647-bce6-a9d5277f703f)

**Comment by kichikuou** [comment]
It looks like you're running an old APK. Please try the [latest version](https://github.com/kichikuou/xsystem4-android/releases/tag/snapshot-20240809).

**Comment by KaroNiko** [comment]
Oops.... Sorry. My fault. I thought the private, interim version (compatible with MG's BBH) was the latest. 😅
Now everything is fine.
