### ISSUE TITLE
[Request] Play from micro-SD card on Android devices.

### ISSUE THREAD

**Issue by KaroNiko** [kichikuou/xsystem4-android#7]
HI. I would like to know if in the future it will be possible to copy games for Xsystem4 to micro SD, perhaps in the same android/data/ folder, and play from there. Why do I ask for it? Well, because I ran out of internal storage space 😅, and these games require a lot of space. For xsystem35-sdl2 I don't think it's possible, because it requires installation from a zip archive, but it would be useful there too. Thank you.

**Comment by kichikuou** [comment]
This app already supports SD cards; I've updated README.md to make that clear.

**Comment by KaroNiko** [comment]
Oh.. I didn't realize that! It's better that way! Another plus point!👍
