### ISSUE TITLE
Is there any way to use PC's save files?

### ISSUE THREAD

**Issue by waldo86p** [kichikuou/xsystem4-android#9]
I just copied my desktop's save files from PC to App's game folder. 
(Android\data\io.github.kichikuou.xsystem4\files\超昂閃忍ハルカ\SaveData)

But there was no change in this app... Save files didn't show up..

**Comment by KaroNiko** [comment]
In your case the right path should be this: Android\data\io.github.kichikuou.xsystem4\files\.xsystem4\超昂閃忍ハルカ\SaveData

**Comment by waldo86p** [comment]
> In your case the right path should be this: Android\data\io.github.kichikuou.xsystem4\files\ .xsystem4\ 超昂閃忍ハルカ\SaveData

Thanks a lot!
